### ISSUE TITLE
Issues deploying to Netlify

### ISSUE THREAD

**Issue by elie222** [SZzzzz/react-scripts-ts-antd#8]
Building locally works fine. When pushing to Netlify we get this issue however:

```sh
6:02:34 PM: yarn run v1.3.2
6:02:34 PM: $ react-scripts-ts-antd build
6:02:34 PM: /bin/sh: 1: react-scripts-ts-antd: not found
```

Any idea why?

Our `package.json` file looks something like this:

```json
  "dependencies": {
	...
    "react-scripts-ts-antd": "2.15.1",
	...
  },
  "scripts": {
    "start": "react-scripts-ts-antd start",
    "build": "react-scripts-ts-antd build",
    "test": "react-scripts-ts-antd test --env=jsdom",
    "eject": "react-scripts-ts-antd eject"
  },
```

**Comment by SZzzzz** [comment]
`react-scripts-ts-antd build` means execute file: 'node_module/.bin/react-scripts-ts-antd'. I guess this file does'n exist on Netlify.

**Comment by joshterrill** [comment]
@elie222 @SZzzzz In order to access that folder in netlify, you just have to make sure `react-scripts-ts-antd` is in your `package.json` dependencies (not devDependencies), and then you can put in your netlify build command settings `./node_modules/react-scripts-ts-antd/bin/react-scripts-ts-antd.js build` and then set the build directory in netlify to `build` and everything should kick off and deploy just fine.
