### ISSUE TITLE
Some SCSS features are not working

### ISSUE THREAD

**Issue by milmaj** [SZzzzz/react-scripts-ts-antd#9]
Some SCC features in .scss files are not working, 

for example comments:
```
// ...
```

or extend:

```
%text {
    line-height: 22px;
}
body {
    @extend %text;
}
```

**Comment by AndreaPontrandolfo** [comment]
Yes i noticed this too. But maybe its actually because here we are using postCSS-preCSS and not SASS.  Also the documentation is a bit unclear about overrriding the default theme styling. Could use a little more detailed explanation on the subject.

**Comment by SZzzzz** [comment]
I am considering replacing precss with node-sass in next version. What do you think about that?

**Comment by AndreaPontrandolfo** [comment]
> I am considering replacing precss with node-sass in next version. What do you think about that?

Absolutly, go ahead. Possibly, Node-sass-chokidar could be a even better solution, i think . I really really wanted to like preCSS, but the documentation is very poor, it's been a pretty terrible experience to work with it, so far. Also, as already pointed out, most of the preCSS features don't work at all right now anyway. Btw, i know very little about Webpack, but i know that CRA already implements PostCSS (because of prefixer). Is it possible to preserve that and place SASS alongside with it? If that's possible that's great. Can't wait for the update, thanks man!

**Comment by AndreaPontrandolfo** [comment]
OR, even better, CRA 2.0 just came to light, and it natively implements SASS and CSS-Modules. It's awesome. Could you try to implement it?
